name: card
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - blas=1.0=mkl
  - bzip2
  - ca-certificates
  - certifi
  - cudatoolkit
  - ffmpeg
  - freetype
  - giflib
  - gmp
  - gnutls
  - intel-openmp
  - jpeg
  - lame
  - lcms2
  - ld_impl_linux-64
  - libffi
  - libgfortran-ng
  - libgfortran4
  - libiconv
  - libidn2
  - libpng
  - libtasn1
  - libtiff
  - libunistring
  - libuv
  - libwebp
  - libwebp-base
  - lz4-c
  - mkl=2023.0.0
  - mkl-service
  - mkl_fft
  - mkl_random
  - ncurses
  - nettle
  - numpy
  - numpy-base
  - olefile=0.46=pyhd3eb1b0_0
  - openh264
  - openssl
  - patsy=0.5.2=pyhd8ed1ab_0
  - pillow
  - pip
  - python
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python_abi=3.8=2_cp38
  - pytorch
  - pytorch-mutex=1.0=cuda
  - pytz=2021.3=pyhd8ed1ab_0
  - readline
  - setuptools
  - six=1.16.0=pyhd3eb1b0_0
  - sqlite
  - statsmodels
  - tk
  - torchaudio
  - torchvision
  - typing_extensions=3.10.0.2=pyh06a4308_0
  - wheel=0.37.0=pyhd3eb1b0_1
  - xz
  - zlib
  - zstd
  - pip:
    - absl-py==1.1.0
    - anyio==3.4.0
    - argon2-cffi==21.1.0
    - astroid==2.12.9
    - attrs==21.2.0
    - babel==2.9.1
    - backcall==0.2.0
    - bleach==4.1.0
    - cachetools==5.1.0
    - cffi==1.15.0
    - charset-normalizer==2.0.7
    - cycler==0.11.0
    - debugpy==1.5.1
    - decorator==5.1.0
    - defusedxml==0.7.1
    - dill==0.3.5.1
    - entrypoints==0.3
    - flake8==5.0.4
    - fonttools==4.28.2
    - google-auth==2.8.0
    - google-auth-oauthlib==0.4.6
    - grpcio==1.47.0
    - idna==3.3
    - importlib-metadata==4.11.4
    - importlib-resources==5.4.0
    - inflect==5.3.0
    - ipykernel==6.5.1
    - ipython==7.29.0
    - ipython-genutils==0.2.0
    - isort==5.10.1
    - jedi==0.18.1
    - jinja2==3.0.3
    - joblib==1.1.0
    - json5==0.9.6
    - jsonschema==4.2.1
    - jupyter-client==7.1.0
    - jupyter-core==4.9.1
    - jupyter-server==1.12.0
    - jupyterlab==3.2.4
    - jupyterlab-pygments==0.1.2
    - jupyterlab-server==2.8.2
    - kiwisolver==1.3.2
    - lazy-object-proxy==1.7.1
    - markdown==3.3.7
    - markupsafe==2.0.1
    - matplotlib==3.5.0
    - matplotlib-inline==0.1.3
    - mccabe==0.7.0
    - mistune==0.8.4
    - nbclassic==0.3.4
    - nbclient==0.5.9
    - nbconvert==6.3.0
    - nbformat==5.1.3
    - nest-asyncio==1.5.1
    - notebook==6.4.6
    - oauthlib==3.2.0
    - packaging==21.3
    - pandas==1.3.0
    - pandocfilters==1.5.0
    - parso==0.8.2
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - platformdirs==2.5.2
    - prometheus-client==0.12.0
    - prompt-toolkit==3.0.22
    - protobuf==3.19.4
    - ptyprocess==0.7.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycodestyle==2.9.1
    - pycparser==2.21
    - pydocstyle==6.1.1
    - pyflakes==2.5.0
    - pygments==2.10.0
    - pylama==8.4.1
    - pylint==2.15.2
    - pyparsing==3.0.6
    - pyrsistent==0.18.0
    - pyyaml==6.0
    - pyzmq==22.3.0
    - requests==2.26.0
    - requests-oauthlib==1.3.1
    - rsa==4.8
    - scikit-image
    - scikit-learn==1.0.1
    - scipy==1.7.2
    - send2trash==1.8.0
    - setuptools-scm==6.3.2
    - sklearn==0.0
    - sniffio==1.2.0
    - snowballstemmer==2.2.0
    - tensorboard==2.9.1
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - terminado==0.12.1
    - testpath==0.5.0
    - threadpoolctl==3.0.0
    - tomli==1.2.2
    - tomlkit==0.11.4
    - torch-tb-profiler==0.4.0
    - tornado==6.1
    - tqdm==4.62.3
    - traitlets==5.1.1
    - urllib3==1.26.7
    - wcwidth==0.2.5
    - webencodings==0.5.1
    - websocket-client==1.2.1
    - werkzeug==2.1.2
    - wrapt==1.14.1
    - zipp==3.6.0
